version: '3.1'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db:
    image: postgres:12
    container_name: "p2pApp"
    env_file:
      - db/database.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: